version : "3"
services:
  db:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_DATABASE: spring_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - 3306:3306